### ISSUE TITLE
Create tweet

### ISSUE THREAD

**Issue by yudium** [yudium/twitter#11]
### TODO
- [ ] Create tweet
- [ ] Create tweet that mentions others
- [ ] Create tweet for maximum 160 chars
- [ ] Create tweet with photos
- [ ] Create tweet with videos
