### ISSUE TITLE
Build Comment

### ISSUE THREAD

**Issue by yudium** [yudium/twitter#2]
### Description

The second most important feature in Twitter after Timeline is Comment as it increases engagement. More engagement more users coming into the app.

### Stories

- [ ] Create a comment
- [ ] Create a comment over another comment
- [ ] Create a comment with photos
- [ ] Create a comment with videos
- [ ] Love comment
- [ ] Retweet comment
- [ ] Retweet quote comment
- [ ] Show total comments in timeline
