### ISSUE TITLE
Verified User

### ISSUE THREAD

**Issue by yudium** [yudium/twitter#7]
### Description

With so many fraudulent accounts on Twitter it would reduce engagements so we need to provide a verification feature for famous people.

### Stories
- [ ] Create verification request page
- [ ] Send verification result email
- [ ] Create verification list page for verification team
